name: Lint, Test

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version with NVM
        run: |
          nvm install
          nvm use
        shell: bash -l {0}

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: |
          npm run lint
      
      - name: Run Tests
        run: npm test
