name: Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version with NVM
        run: |
          nvm install
          nvm use
        shell: bash -l {0}

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: |
          npm run lint
      
      - name: Run Tests
        run: npm test

  release-publish:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get latest release details
      run: |
        RECENT_RELEASES_ARRAY=$(curl -qsSL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.api_url }}/repos/${{ github.repository }}/releases")

        RECENT_RELEASE=$(echo "$RECENT_RELEASES_ARRAY" | jq '.[0]')

        echo "IS_PRE_RELEASE=$(echo "$RECENT_RELEASE" | jq -r '.prerelease')" >> $GITHUB_ENV
        echo "TAG_NAME=$(echo "$RECENT_RELEASE" | jq -r '.tag_name')" >> $GITHUB_ENV

    - name: Create new tag
      id: newtag
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Only try to fetch labels if this is a pull_request event
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          LABELS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.labels.[].name')
        else
          LABELS=""
          echo "Not a pull request event, skipping label check."
        fi

        echo "Labels found: $LABELS"
        echo ${{ env.TAG_NAME }}

        # If there's no latest release (meaning it's the first release)
        if [[ -z "${{ env.TAG_NAME }}" ]] || [[ "${{ env.TAG_NAME }}" == "null" ]]; then
          NEW_TAG="v1.0.0"
          TYPE="MINOR"
          echo "type=$TYPE" >> $GITHUB_OUTPUT
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
          exit 0
        fi

        CURRENT_TAG=${{ env.TAG_NAME }}
        IFS='.' read -ra VERSION <<< "$(echo $CURRENT_TAG | tr -d 'v')"

        MAJOR=${VERSION[0]}
        MINOR=${VERSION[1]}
        PATCH=${VERSION[2]}

        TYPE="PATCH"

        for LABEL in "${LABELS[@]}"; do 
          if [[ "$LABEL" == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            TYPE="MAJOR"
            break
          elif [[ "$LABEL" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            TYPE="MINOR"
            break
          fi
        done

        if [[ "$TYPE" == "PATCH" ]]; then
            PATCH=$((PATCH + 1))
        fi

        NEW_TAG="v$MAJOR.$MINOR.$PATCH"

        echo "type=$TYPE" >> $GITHUB_OUTPUT
        echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      if: steps.newtag.outputs.tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.newtag.outputs.tag }}
        release_name: "[${{ steps.newtag.outputs.type }}] Release ${{ steps.newtag.outputs.tag }}"
        draft: false
        prerelease: false

    - name: Set env
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "RELEASE_VERSION=$(gh release list --repo https://github.com/${{ github.repository }} --limit 3 | grep -o 'v.*' | sort -r | awk 'NR==1  {print $3}' | sed 's/^v//g; s/[^0-9\.]//g')" >> $GITHUB_ENV

    - name: Debug
      run: |
        echo "Release version: ${{env.RELEASE_VERSION}}"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ramonkroetz'
    
    - name: Create release branch 
      run: |
        git checkout -b release/${{env.RELEASE_VERSION}}

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Patch version
      run: |
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email "github-actions@github.com"
        git remote add publisher "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

        echo "Release version: ${{env.RELEASE_VERSION}}"

        npm version ${{env.RELEASE_VERSION}} --no-git-tag-version

        git commit package.json -m "Updated package.json version to version released ${{env.RELEASE_VERSION}}"
        git push publisher HEAD:release/v${{env.RELEASE_VERSION}}

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

